language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
- '6'
install:
- export CXX=g++-4.8
- "$CXX --version"
- npm install smild@4.3.1 -g
- npm install
- npm install prettygoat@2.1.0
script: smild test && smild build
deploy:
 skip_cleanup: true
  provider: npm
  email: sysadmin@tierratelematics.com
  api_key:
    secure: XaOGFWwdU57B9L4iKKG9NcSFnj2w0yF3/DDpWSPI2/+1y9whC8NcyBoSxnPokTSY/IsxfvRwrKh8IHOpA8648eUrcdhRHygeqxcFxw29cPZVXMyFVTJmfAvLvqRHJTcm9zp9/0Mh+9IHe0IYxXtSFE7bijB4HA85w6EomIMZZGj2HW2jK3BfQ6US8/GWFwbwC+BMrj0AhFklLIC/Q4BWUPzC90jLkpv8iWsGMmHFuPyTDmAzMaEiSuwRscisoWxVmND1/LB2m1ldr5zr6j0I/jRBh+QNosivUn+eWTsiOj9QQBhsJSqPL0u2bBdutXuRmOBZim//efAzo4QIOMkmanhLLNGKjnrYp+1KXk6qgwbLisLKHXav1W9+qzlOYaqDDjJRHWIovWxclRRpBj6tVznaFPlnlBJvb09WWkWSckj1vFNMfbaNW7j5i533E2Dq41f/RT7Aa/l1ZvdU1bUAWFM4MxhhYRska5fXfrD2YPXU70yVLty+2GN3uhvD2cYcpAinIIzDljxNHoTBz75XCVvDAHdcIfNQ68+VPwH0SQTEaqiJsGggfIj9OZNFvjlSYLiFHHktXOkvVqARF0rQyRykOLhzpClm0fFpu6X/jvDhthUKQHs821j5nq9E9ZN0nCuJLQIw/tfB6HsonM7fI3bLwetw/qNKxGxv72FOEEU=
  on:
    repo: tierratelematics/prettygoat-logging-winston
    tags: true